name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build: docker build -t krystism/super_mario_crossover:3.1.21 .

    runs-on: docker run -p 9999:80 krystism/super_mario_crossover:3.1.21

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
